### PR TITLE
port drive on heading behavior to new gazebo

### PR DESCRIPTION
**Pull request by stevedanomodolor**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |

---

## Description of contribution in a few bullet points
* Port drive on heading behavior to new gazebo.
* Related issue https://github.com/ros-navigation/navigation2/issues/4455

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
I'm seeing this fail 2x in a row, I'm rerunning against from start to check, but there may be something up with this one.

**Comment by stevedanomodolor** [comment]
Yeah, this behavior seems to happen with  behavior tests. I am not sure either that. I will put it on draft untill i figure out why

**Comment by SteveMacenski** [comment]
Yeah, these aren't flaky, they're just failing most of the time :/ I suppose we could bin these under #4349 as 'fix and rewrite'? I think they all fail from the same kinds of issues of trying to do some really strange faking out of the behaviors. Similar to migrating to GZ, I think this is similarly a "figure it out once: copy paste for the rest"

Please do put in draft

**Comment by SteveMacenski** [comment]
@stevedanomodolor I'm pulling this into https://github.com/ros-navigation/navigation2/pull/4515 as I'm just rewriting the tests altogether with your base work on adding the new gazebo!

**Pull request closed without merging**
