### PR TITLE
Pass IDLE to on_tick, use that for initialize condition

### PR DESCRIPTION
**Pull request by redvinaa**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |#3988 |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | – |
| Does this PR contain AI generated software? | No|

---

## Description of contribution in a few bullet points

* Pass IDLE state to BT action nodes (to the on_tick callback), and use that as initialize condition
* This way ports can be updated at every restart (on first start and after each halt)
* See conversation at the bottom of #3988

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
I see no issues with this, LGTM once CI passes :-) 

Thanks for bringing this to our attention!

**Comment by SteveMacenski** [comment]
@redvinaa it looks like 1 test is failing (ignore DWB; that's occasionally flaky)

**Comment by redvinaa** [comment]
I have no idea why that particular test failed. It's possible that a rerun would solve it.

**Comment by SteveMacenski** [comment]
I triggered a rebuild, but I don't expect that to change, a unit test like that shouldn't be flaky

**Comment by redvinaa** [comment]
Found it: the subscriber was always recreated in `initialize`, and as in the test we spin first and then tick, the callback was always called with the old inputs. Changed `initialize` to only create new subscriber when the topic has changed (or in the beginning when the sub doesn't exist yet).

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
