### PR TITLE
[loopback_sim] Publish clock, [nav2_costmap_2d] Fix Qos

### PR DESCRIPTION
**Pull request by adivardi**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation of TB4 |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

- loopback_simulator: Publish `/clock`, so there is a clock available for all other nodes. Without a clock published, the local & global costmaps are not published, so they don't appear on rviz.
- Costmap_2d: Use QoS profile from `rclcpp::SensorDataQoS()` instead of `rmw_qos_profile_t`. This solves an issue where the subscriber uses `RELIABLE` setting even when initialized from `rmw_qos_profile_sensor_data`. In addition the `Subscriber(..., rmw_qos_profile_t)` constructor is anyway deprecated in favor of `Subscriber(..., rclcpp::QoS)`
- Small typos in Smac Planner's README

## Description of documentation updates required from your changes

Added new parameter with True by default in the launch file. Already added to the package's README. need to add that to default configs and documentation page

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — COMMENTED** [review]
Can you add the new parameter to the configuration guide for the node? Then we can merge the pair https://github.com/ros-navigation/docs.nav2.org/blob/master/configuration/packages/configuring-loopback-sim.rst

**Comment by adivardi** [comment]
> Can you add the new parameter to the configuration guide for the node? Then we can merge the pair [ros-navigation/docs.nav2.org@`master`/configuration/packages/configuring-loopback-sim.rst](https://github.com/ros-navigation/docs.nav2.org/blob/master/configuration/packages/configuring-loopback-sim.rst)

in https://github.com/ros-navigation/docs.nav2.org/pull/600

**Comment by SteveMacenski** [comment]
@adivardi commented on that.  A minor issue and I can merge the pair. Thanks!

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Sorry for the delay, we had ROSCon, ROS-I, and then I took a short vacation while in Europe. I'm getting back to work this morning :-)

**Pull request merged**
