### PR TITLE
Humble compatibility for watchdog mechanism

### PR DESCRIPTION
**Pull request by Aadi0902**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on |  |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

This PR adds a per source blocking watchdog mechanism, i.e. stop the robot if a source is not publishing at the expected rate (building on the existing source_timeout mechanism) for **humble**. This feature already exists on main following [PR 3880](https://github.com/ros-navigation/navigation2/pull/3880)

## Description of documentation updates required from your changes
-

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by SteveMacenski** [comment]
This is not able to be backported since the API changes return types. Unfortunately this is why this was not backported originally.

**Comment by SteveMacenski** [comment]
Closing due to aforementioned reason. If you can re-implement the feature in a backportable way (no API changes), I'm happy to review / merge that!

**Comment by Aadi0902** [comment]
> Closing due to aforementioned reason. If you can re-implement the feature in a backportable way (no API changes), I'm happy to review / merge that!

@SteveMacenski  quick question: though the proposed changes do change function definitions, what are the implications of changing return type from void to bool? technically it should still support any use case where the function was used as void right?

**Comment by SteveMacenski** [comment]
If anyone else created derivative classes of those classes, they would stop compiling after a Humble sync. Additionally a struct was changed with similar consequences

**Pull request closed without merging**
