### PR TITLE
Improve Docking panel

### PR DESCRIPTION
**Pull request by ajtudela**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #4689 |
| Primary OS tested on | Ubuntu 24.04 |
| Robotic platform tested on | Morphia robot |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

* Improved internal state machine to fix randomly RVIZ crashes.
* Improved the UI.

| Captura desde 2024-10-07 12-43-26 | Captura desde 2024-10-08 11-06-38 |
| -------- | ------- |
| *Before* | *After* |

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by stevedanomodolor** [comment]
I also noticed this issue too. Rviz crashes when using simulation with the docker.  I noticed it was docking because removing the following the rviz setting, it works as usual. 
  # - Class: nav2_rviz_plugins/Docking
  #   Name: Docking

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
This looks great @ajtudela thanks for the update! Definitely better organized :-)

**Comment by evshary** [comment]
Thank you for the fix! Could I know whether the PR will be backported to Jazzy?

**Comment by SteveMacenski** [comment]
Lets see if the bot can do it automatically

**Comment by SteveMacenski** [comment]
The auto-backport failed. @ajtudela can you cherry pick it to jazzy and fix the issue in the hpp file? I took a look (^ PR above) and seems more suited to the author than something I can knock out in a couple of minutes.

**Comment by ajtudela** [comment]
Done!! #4725

**Pull request merged**
