### PR TITLE
[RPP] add is_rotating_to_heading feedback

### PR DESCRIPTION
**Pull request by doisyg**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Dexory robot |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

A draft first to discuss, I would be interested in the feedback of RPP users. cc @james-ward 

This PR adds the publisher topic `is_rotating_to_heading` in order to feedback to an external system if RPP is currently rotating to align with the path or final pose. 
A situation that happens either if `shouldRotateToGoalHeading(carrot_pose)` or `shouldRotateToPath(rotate_to_path_carrot_pose, angle_to_heading, x_vel_sign)` is true.

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
No issue with the implementation, though curious on the need. Feel free to merge when you're satisfied

**Comment by doisyg** [comment]
> No issue with the implementation, though curious on the need. Feel free to merge when you're satisfied

Scanning application where I want to start scanning only after RPP is aligned with the path I want to scan. Hence I need the feedback

I will wait a bit to see if @james-ward has any feedback, and then we can merge!

**Comment by SteveMacenski** [comment]
Do you want it actively or passively (i.e. need event based topics or query based)? A parameter or service could also work. Also I was thinking that a diagnostic message with that instead could be useful. 

Any way, happy with this PR, just some thoughts

**Comment by doisyg** [comment]
Active, and published in sync with the Twist is perfect for me. So as it is currently (I could use diagnostic too but a Bool topic seems simpler to produce and consume to me).
Leaving it open for 24h and then I will merge

**Pull request merged**
