### PR TITLE
Make RecoveryNode return Running

### PR DESCRIPTION
**Pull request by tonynajjar**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |

---

## Description of contribution in a few bullet points

See https://github.com/ros-navigation/navigation2/issues/4776

## Description of documentation updates required from your changes

We need to think how that might affect users

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — COMMENTED** [review]
No objections to the fix, but if we do this, is the `while` loop even important anymore? We could just do an `if (retry_count_ > number_of_retries_) {halt(); return FAILURE;}` and the rest could be without the additional scope, no? I think this is the only purpose that the `while` loop holds

**Comment by tonynajjar** [comment]
> No objections to the fix, but if we do this, is the `while` loop even important anymore? We could just do an `if (retry_count_ > number_of_retries_) {halt(); return FAILURE;}` and the rest could be without the additional scope, no? I think this is the only purpose that the `while` loop holds

good point, fixed.

**Comment by tonynajjar** [comment]
Looking at the PipelineSequence, it also has something similar [here](https://github.com/angsa-robotics/navigation2/blob/fix-recoverynode/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp#L53). After SUCCESS, shouldn't we be saving a state and return RUNNING?

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
These must have been written by the same person. I'd merge a PR to do the same thing as here for that as well :-)

**Comment by tonynajjar** [comment]
Follow up ticket: https://github.com/ros-navigation/navigation2/issues/4782

**Pull request merged**
