### PR TITLE
`Shim Controller`: Added parameter `rotate_to_heading_once` to align a robot only at the very beginning

### PR DESCRIPTION
**Pull request by ikhann**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Differential Robot, Gazebo) |
| Does this PR contain AI generated software? | (No) |

---

## Description of contribution in a few bullet points

* Added a new dynamic parameter called `rotate_to_heading_once`.
If the parameter is set to `True`, then `Shim` aligns the robot's heading with the path only once at the very beginning.

* Added a method `bool RotationShimController::isGoalChanged(const nav_msgs::msg::Path & path)`
  This function checks whether the goal in the provided path has changed compared to the current path stored in the controller.
   **Returns `true`** if the current path is empty (no poses stored) or if the goal pose (last pose in the path) differs from the goal pose of the provided path.

## Description of documentation updates required from your changes

Example: 
```
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.785
      angular_disengage_threshold: 0.25
      rotate_to_heading_once: True
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 1.8
      max_angular_accel: 3.2
      simulate_ahead_time: 1.0
```

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by SteveMacenski** [comment]
However, you need to fix the linting issues and DCO sign offs that are missing on this PR that CI has pointed out.

**Comment by ikhann** [comment]
> However, you need to fix the linting issues and DCO sign offs that are missing on this PR that CI has pointed out.

Thanks! I'll fix the linting issues and other stuff shortly.

**Comment by SteveMacenski** [comment]
@ikhann still a few linting errors if you look at the ament_cpplint and ament_uncrustify jobs

**Comment by ikhann** [comment]
> @ikhann still a few linting errors if you look at the ament_cpplint and ament_uncrustify jobs

Everything should be good now.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Great thanks!

**Pull request merged**
